name: Delete Windows prereleases related to deleted branch
on:
  delete

jobs:
  delete_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=version;]$(python run.py --version)"
      id: extract_version

    - name: Delete non-master branch release
      uses: author/action-rollback@stable
      with:
        tag: ${{ steps.extract_version.outputs.version }}
        always_delete_tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
